### ISSUE TITLE
docker plugin install juicedata/juicefs:1.1.0 error

### ISSUE THREAD

**Issue by snake1817** [juicedata/docker-volume-juicefs#34]
# context
docker 20.10.24
ubuntu 20.4
image version juicedata/juicefs:1.1.0 
# install command
sudo docker plugin install juicedata/juicefs:1.1.0 --alias juicefs
# full error detail
**Error response from daemon: 
failed to create shim task: 
OCI runtime create failed: 
runc create failed: 
unable to start container process: 
error during container init:
error mounting "/etc/resolv.conf" to rootfs at "/etc/resolv.conf": 
stat /etc/resolv.conf: no such file or directory: unknown**

**Comment by timfeirg** [comment]
your docker is trying to mount /etc/resolv.conf into the volume plugin container, but since /etc/resolv.conf doesn't exist in the host file system, it fails to do so.

could you verify /etc/resolv.conf actually exists on the host itself?

**Comment by snake1817** [comment]
> your docker is trying to mount /etc/resolv.conf into the volume plugin container, but since /etc/resolv.conf doesn't exist in the host file system, it fails to do so.
> 
> could you verify /etc/resolv.conf actually exists on the host itself?
this error in the install plugin , not docker run

**Comment by snake1817** [comment]
> your docker is trying to mount /etc/resolv.conf into the volume plugin container, but since /etc/resolv.conf doesn't exist in the host file system, it fails to do so.
> 
> could you verify /etc/resolv.conf actually exists on the host itself?

 /etc/resolv.conf  this file really not exist , I repaired this file later，install plugin success ^ ^
