### ISSUE TITLE
系统重启后挂载失败，要强制停止插件再升级插件才能使用

### ISSUE THREAD

**Issue by zzerding** [juicedata/docker-volume-juicefs#37]
使用的mate为https://juicefs.com/static/juicefs 配合腾讯云oos.正常客户端使用没问题，使用docker plugin 系统重启后就挂载失败。volumes里没有数据。请问应该怎么排查？

`docker info`
```shell
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
    Kernel Version: 5.10.0-26-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Live Restore Enabled: false
```
按照https://juicefs.com/docs/zh/community/juicefs_on_docker#troubleshooting   排查，输出如下：

sudo. ls /run/docker/plugins/runtime-root/plugins.moby 输出为空
sudo runc --root /run/docker/plugins/runtime-root/plugins.moby list 没有输出

`sudo journalctl -f -u docker | grep "plugin="` 输出如下
```shell
" level=error msg="2024/01/04 10:29:50 Entering go-plugins-helpers getPath" plugin=2894f5d961070ef3a4cfd1c79f46ec8f66a7a9dd4ea2e7c5507e5fcbb286135e
" level=error msg="2024/01/04 10:29:50 Entering go-plugins-helpers capabilitiesPath" plugin=2894f5d961070ef3a4cfd1c79f46ec8f66a7a9dd4ea2e7c5507e5fc
```
已知可用的解决方案为：
`docker plugin disable --force juicedata/juicefs && docker plugin upgrade juicedata/juicefs`
然后重新启动容器

**Comment by TechQuery** [comment]
文档说 Docker compose 停机时要执行：
```shell
docker-compose down --volumes
```
但始终报错：
```text
Error response from daemon: remove my_juice: VolumeDriver.Remove: exit status 1
```
手动删卷也一样：
```shell
sudo docker volume rm -f my_juice
```

**Comment by TechQuery** [comment]
> 已知可用的解决方案为：
> `docker plugin disable --force juicedata/juicefs && docker plugin upgrade juicedata/juicefs`
> 然后重新启动容器

@zzerding 用了这条命令倒是删了旧卷，但 `enable` 后再 `docker-compose up` 就又报错：
```text
ERROR: create api-service_polyfill-buffer: VolumeDriver.Create: exit status 1
```

**Comment by timfeirg** [comment]
format 命令允许重复多次执行的，如果文件系统已经存在，会跳过。因此能否：

* 确认下你用的是最新版 docker volume plugin
* 启用 debug：https://github.com/juicedata/docker-volume-juicefs/?tab=readme-ov-file#debug

然后将日志中的 format 命令脱敏发一下 @zzerding

**Comment by luojiyin1987** [comment]
https://github.com/juicedata/juicefs/blob/59659db8d67af0934836076a98e205f08fdf924d/cmd/format.go#L482-L505

是不是触发报错的逻辑代码？  @timfeirg 
```shell
juicefs[12] <FATAL>: Storage wasb://polyfill4web/polyfill-buffer/ is not empty; please clean it up or pick another volume name [format.go:485]
```

**Comment by timfeirg** [comment]
是这个代码没错，但 format 命令本身是可以反复执行的，如果走到了 create = true 的条件分支，说明元数据引擎是一片空白、需要 format 的状态，但又因为对象存储的对应路径不为空，所以进入冲突。

需要梳理你的使用流程，为什么会反复清空引擎，却未清空对象存储数据呢？

**Comment by TechQuery** [comment]
> 需要梳理你的使用流程，为什么会反复清空引擎，却未清空对象存储数据呢？

我的上下文代码在此：wessberg/Polyfiller#71

**Comment by timfeirg** [comment]
每次运行的时候，都现场创建一个sqlite作为元数据引擎。现场销毁以后，对应的对象存储却并未清空。导致下次即便想复用，也会报错。

可以选择：

* 每次运行之前，都清空对象存储，让 juicefs 客户端得以全新 format 文件系统
* 或者复用一个持久存续的元数据引擎，这样就不需要每次都重新 format 一个了

目前看来，这不是 docker volume plugin 的问题，而是 juicefs 创建和使用流程的问题，先 close 了

**Comment by TechQuery** [comment]
> 每次运行的时候，都现场创建一个sqlite作为元数据引擎。现场销毁以后，对应的对象存储却并未清空。导致下次即便想复用，也会报错。
> 
> 可以选择：
> 
> * 每次运行之前，都清空对象存储，让 juicefs 客户端得以全新 format 文件系统
> * 或者复用一个持久存续的元数据引擎，这样就不需要每次都重新 format 一个了
> 
> 目前看来，这不是 docker volume plugin 的问题，而是 juicefs 创建和使用流程的问题，先 close 了

Docker compose 配置文件是按照官方文档写的，但上面并没有写如何销毁元数据存储。所以按理说，应该在 Docker 镜像正常退出的时候，插件自动做好清理工作。

**Comment by timfeirg** [comment]
可以用 juicefs destroy 来销毁文件系统，但这不是 docker volume plugin 的工作。文件系统必须用户显式操作、销毁。

jfs 和周边系统（docker volume plugin，或者 csi 驱动）都将文件系统视作「重要、决不能乱删」的资源，在你的例子里，应该是 CI 环境销毁的时候直接删了 sqlite 文件，但是并没有流程负责清理对象存储，这才导致下次启动的时候没办法重新跑 format。

在一个正常的业务场景中，绝不会有人去乱删元数据引擎的数据，如果要销毁文件系统，那也应该走正常流程、用 destroy 命令来清空两边的数据。

docker volume plugin 不可能去在 volume 卸载或删除的时候，来清空你的元数据引擎，这会在业务中导致灾难（因为也许其他应用还在使用这个文件系统，并且不一定会通过 volume plugin）

**Comment by timfeirg** [comment]
举个更简明的例子，你的诉求就像是应用连接 mysql，创建 db，然后指望应用关停以后，mysql 能自动把这个 db 给销毁掉，这不符合正常应用的使用流程，因此 jfs volume plugin 也无法实现你期望的自动清理，不属于“甩锅”。

**Comment by TechQuery** [comment]
> 可以用 juicefs destroy 来销毁文件系统，但这不是 docker volume plugin 的工作。文件系统必须用户显式操作、销毁。
> 
> jfs 和周边系统（docker volume plugin，或者 csi 驱动）都将文件系统视作「重要、决不能乱删」的资源，在你的例子里，应该是 CI 环境销毁的时候直接删了 sqlite 文件，但是并没有流程负责清理对象存储，这才导致下次启动的时候没办法重新跑 format。
> 
> 在一个正常的业务场景中，绝不会有人去乱删元数据引擎的数据，如果要销毁文件系统，那也应该走正常流程、用 destroy 命令来清空两边的数据。
> 
> docker volume plugin 不可能去在 volume 卸载或删除的时候，来清空你的元数据引擎，这会在业务中导致灾难（因为也许其他应用还在使用这个文件系统，并且不一定会通过 volume plugin）

@timfeirg  我不想清理、不想销毁呀，我就是想能丝滑重启容器，没别的需求。

我最早只执行docker compose down，再次docker compose up的时候，Docker说已经有同名卷了，让我先销毁。

于是我又按JuiceFS文档执行docker compose down --volumes来销毁卷，但JuiceFS又报退出码1。

然后我又重启插件试图手动销毁存储，但再次启动容器时又报创建卷退出码是1，日志里说已经存在数据库文件不让我创建……

**Comment by TechQuery** [comment]
> 举个更简明的例子，你的诉求就像是应用连接 mysql，创建 db，然后指望应用关停以后，mysql 能自动把这个 db 给销毁掉，这不符合正常应用的使用流程，因此 jfs volume plugin 也无法实现你期望的自动清理，不属于“甩锅”。

@timfeirg 我作为一个Docker用户，我就是想在我的应用代码更新的时候重启相关服务的容器，同时复用现有所有的卷。

我现在根本涉及不到任何销毁数据的需求，因为我是要提供一个长期的对外服务。现在所有的“销毁”都是日志和issue当中跟我说：你得先销毁，再怎样…… 都把我绕晕了。

**Comment by naisanzaa** [comment]
so is this problem resolved? I just read through all the links and seems like it's still unstable when using as a docker volume plugin.

**Comment by timfeirg** [comment]
there are no known issues, but overall, using docker volume plugin is not encouraged, troubleshooting on the plugin is more difficult due to its architecture, and zero-downtime restart and upgrade is not supported. maybe you should consider mounting JuiceFS directly on host, and volume the host path to the container. @naisanzaa
